
#定義一個工作流名稱
name: Test and release ASM

#定義觸發工作流的事件，這裡是每當有push或pull request時
on: [push, pull_request]

#定義一個工作流中的任務
jobs:

  #定義一個任務名稱
  build:

    #定義運行任務的操作系統，這裡是ubuntu-latest
    runs-on: ubuntu-latest

    #定義任務中的步驟
    steps:

      #第一步，使用actions/checkout@v2動作來檢出代碼
      - name: Checkout code
        uses: actions/checkout@v2

      #第二步，使用apt-get命令來安裝NASM和ld工具
      -  name: Install NASM and ld
         run: sudo apt-get install nasm binutils

      #第三步，設置asm_name
      -  name: Read...
         env:
            filename: ${{secrets.asm_name}}
         run: echo ${filename}


      #第四步，使用nasm命令來編譯asm文件，生成對象文件
      -  name: Compile asm file
         run: nasm -f elf64 ${filename}.asm -o ${filename}.o

      #第五步，使用ld命令來鏈接對象文件，生成執行檔
      -  name: Link object file
         run: ld ${filename}.o -o ${filename}

      #第六步，創建一個release，並把release的ID傳遞給下一個步驟
      -  name: Create a release
         uses: "marvinpinto/action-automatic-releases@latest"
         with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          files: |
              ./*